[package]
name = "Aptos"
version = "0.0.0"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "main" }

[addresses]
Wormhole="f99fef4e49c63ccc450b4d94556e720e7e5a06ad7aa6c8b67c79adbc7c194e96"
std = "0x1"
aptos_std = "0x1"
aptos_framework = "0x1"

