apiVersion: v1
kind: Service
metadata:
  labels:
    app: aptos
  name: aptos
spec:
  ports:
    - name: node
      port: 5001
      targetPort: node
    - name: prometheus
      port: 9184
      targetPort: prometheus
  selector:
    app: aptos
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: aptos
  name: aptos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aptos
  serviceName: aptos
  template:
    metadata:
      labels:
        app: aptos
    spec:
      containers:
        - name: aptos-node
          image: aptos-node
          command:
            - /bin/sh
            - -c
            - /tmp/start_node.sh
          ports:
            - containerPort: 5001
              name: node
              protocol: TCP
            - containerPort: 9184
              name: prometheus
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: 5001

      restartPolicy: Always
